[package]
name = "fracgm-cxx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
ndarray = "0.15.6"
fracgm = { path = "../fracgm" }
libc = "0.2.155"
