# Copyright 2024 the FracGM authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

import typing as T

import numpy.typing as npt

class IterationComponent:
    @property
    def alpha_vec(self) -> npt.ArrayLike: ...
    @property
    def alpha_mat(self) -> npt.ArrayLike: ...
    @property
    def alpha_proj(self) -> npt.ArrayLike: ...
    @property
    def beta(self) -> T.List[float]: ...
    @property
    def mu(self) -> T.List[float]: ...
    @property
    def psi_norm(self) -> T.List[float]: ...

class Diagnostic:
    @property
    def iterations(self) -> T.List[IterationComponent]: ...
    @property
    def solution(self) -> npt.ArrayLike: ...
    @property
    def n_iters(self) -> int: ...
